PURRSOFT 71.1 Added Change Password endpoint & updates Animal Command…
PurrSoft/purrsoft-backend pull request #9
Opened 2024-11-28 20:28 UTC by Paula-H

…s, Filters, Controller

2024-11-29 10:59 UTC, Domynis requested changes

2024-12-03 19:12 UTC, Domynis approved these changes
LGTM

2024-12-03 19:22 UTC, raulfrandes approved these changes
lgtm

2024-12-07 20:02 UTC, florinacho337 requested changes
Daca se incearca adaugarea unui animal cu sterilized: false (sau se actualizeaza la false), se returneaza urmatoarea eroare, cod 500:
FluentValidation.ValidationException: Validation failed: 
 -- animalDto.Sterilized: 'animal Dto Sterilized' must not be empty. Severity: Error
 
La change password, se poate pune o parola cu mai putin de 8 caractere si fara cifre.
De asemenea, nu se verifica daca exista un token (adica poate modifica oricine parola oricui).

In rest totul ok :D

2024-12-11 06:59 UTC, florinacho337 approved these changes

2024-12-11 07:09 UTC, merged